name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    strategy:
      matrix:
        os: [ macos-latest, macos-12 ]

    runs-on: ${{ matrix.os }}
    continue-on-error: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          
      - name: Show XCode Version
        run: xcode-select -p

      - name: Build QMedia Framework
        run: ./dependencies/build-qmedia-framework.sh

      - name: Build Decimus
        env:
          scheme: Decimus
        run: |
          brew install swiftlint
          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
          xcodebuild clean build -scheme "$scheme" -"$filetype_parameter" "$file_to_build" | xcpretty && exit ${PIPESTATUS[0]}

      - name: Archive Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Decimus
          path: $file_to_build

